### ISSUE TITLE
Missing icons and menu(s)

### ISSUE THREAD

**Issue by kjellp** [EGA-archive/FEGA-Portals#3]
**FEGA node**
Norway

**Affected portal**
Submitter Portal (test and prod)

**Describe the bug**
Icons for the different steps in the submission process is missing, as well as the menus around the Username top right (including logout)  and menu in the bar below the user name (For different types of objects).

**To Reproduce**
1. Login to submission portal
2. Open a submission

**Expected behavior**
Icons and menus to return and operat as usual/intended :)

**Screenshots**
Attached
![Screenshot from 2024-09-05 11-06-07](https://github.com/user-attachments/assets/8b702ae6-be07-48c1-8dc1-214814fc21d7)

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - Browser: Firefox
 - Version:  128.0 (64-bit)

**Additional context**

**Comment by sdelatorrep** [comment]
Hi Kjell! We detected this issue on the 5th, and it was caused by the problem with a kit from fontawesome that stopped being available. We fixed it in production portals on the same day, and in test on the next day. 
We're also working on a long term solution that prevents this from happening again.
Thanks for reporting!
