### ISSUE TITLE
Difficult to add collaborators to a submission

### ISSUE THREAD

**Issue by elisavettorstensson** [EGA-archive/FEGA-Portals#6]
**FEGA node**
Sweden

**Affected portal**
Submitter Portal

**Describe the bug**

**What I tried to do**
I tried to add a collaborator to a submission after starting the creation of my “New submission.” I tried the following methods:

- Writing or copying and pasting the first and last name of my collaborator in the field 'User'.
- Copying and pasting the email address of my collaborator in the field 'User' .
**OBS** I used firefox as a browser

**What actually happened**
It was only possible to add my collaborator by manually typing the **full** email address.

**Expected behavior**
- I expected to be able to add my collaborator when I provided their first and last name. 
- I expected the system to recognize and find my collaborator after typing part of their email address, not the entire address. 
- I expected that when I copy-pasted the email address, the system would recognize it, and I could add my collaborator.

**To Reproduce**
1. Create a new submission.
2. In the window 'New Submission', check the box 'Add Collaborators'.
3. In the section 'Search Collaborators', select 'User'.
4. In the field 'Search for a User...', search for a collaborator to add by the previous actions specified above.

**Screenshots**
![image](https://github.com/user-attachments/assets/7b238101-d3f1-4cff-992a-aea458ba4b91)

**Environment (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser (incl. version): Firefox Version 115.15.0esr (32-bit)
 - Version: 10

**Comment by elisavettorstensson** [comment]
Among our Helpdesk team members, we tried different browsers and various approaches. For some, Google Chrome works without any issues, while for others, Firefox also works fine. In my case, I used Firefox, and it worked when I copied and pasted the email address and then pressed space to find the collaborators. I'm not sure if it's a significant issue, but some people are experiencing problems.

**Comment by ainajene** [comment]
Thank you for reporting this issue, @elisavettorstensson !

We appreciate your feedback. However, we'd like to clarify that the behaviour you experienced when adding collaborators is intentional and designed in accordance with GDPR guidelines.

Under GDPR, we are required to protect user data and ensure that personal information, such as names and email addresses, is not exposed without consent. Displaying user details (such as matching users based on partial information) would violate this regulation, as it could potentially reveal identifiable information without the explicit consent of the user involved.

To comply with GDPR, we limit the visibility of user data to ensure their privacy is protected. As a result, the system currently only allows the addition of collaborators by manually entering the full email address, which ensures that sensitive data is not inadvertently exposed as you should know the email in advance.
